# Generated by Django 5.2 on 2025-05-07 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('basic_salary', models.DecimalField(decimal_places=2, max_digits=20)),
                ('tax_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('bonus', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('other_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('net_salary', models.DecimalField(decimal_places=2, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.employee')),
            ],
        ),
        migrations.DeleteModel(
            name='Payslip',
        ),
    ]
